"""Status surfaces and disclosures, independent of backup execution."""
from PySide6.QtCore import Qt
from PySide6.QtWidgets import QWidget, QScrollArea, QFrame, QVBoxLayout, QHBoxLayout, QFormLayout, QLabel, QProgressBar, QPlainTextEdit, QPushButton, QApplication
from .common import DisclosureSection
import consumer

class StatusPage(QScrollArea):
    CONTROL_NAMES = ('activity_rows', 'backup_explanation', 'backup_progress', 'copy_summary_button', 'details_section', 'history_section', 'lbl_check', 'lbl_dest', 'lbl_dest_reason', 'lbl_dest_status', 'lbl_headline', 'lbl_last', 'lbl_last_attempt', 'lbl_next', 'lbl_progress_detail', 'lbl_repo', 'lbl_restore_test', 'lbl_verify', 'left_panel', 'log_section', 'log_view', 'summary_surface')

    def __init__(self):
        super().__init__()
        self.setWidgetResizable(True)
        self.setFrameShape(QFrame.NoFrame)
        canvas = QWidget()
        outer = QVBoxLayout(canvas)
        outer.setContentsMargins(20, 20, 20, 20)
        self.left_panel = QWidget()
        self.left_panel.setObjectName("leftPanel")
        content = QVBoxLayout(self.left_panel)
        content.setContentsMargins(0, 0, 0, 0)
        content.setSpacing(12)
        outer.addWidget(self.left_panel)
        self.setWidget(canvas)
        self.summary_surface = QWidget()
        self.summary_surface.setObjectName("summarySurface")
        self.summary_surface.setAttribute(Qt.WA_StyledBackground, True)
        summary = QVBoxLayout(self.summary_surface)
        summary.setContentsMargins(24, 22, 24, 22)
        summary.setSpacing(14)
        summary.addWidget(QLabel("Backup status"))
        self.lbl_headline = QLabel()
        font = self.lbl_headline.font()
        font.setBold(True)
        font.setPointSize(font.pointSize() + 4)
        self.lbl_headline.setFont(font)
        self.lbl_headline.setWordWrap(True)
        summary.addWidget(self.lbl_headline)
        self.backup_explanation = QLabel("Keep saves a new version of your selected files. Earlier backups remain available according to your retention settings. The backup location is not erased.")
        self.backup_explanation.setWordWrap(True)
        summary.addWidget(self.backup_explanation)
        form = QFormLayout()
        form.setHorizontalSpacing(20)
        form.setVerticalSpacing(12)
        form.setRowWrapPolicy(QFormLayout.WrapLongRows)
        self.lbl_last, self.lbl_next = QLabel(), QLabel()
        for label in (self.lbl_last, self.lbl_next):
            label.setWordWrap(True)
        form.addRow("Last backup", self.lbl_last)
        form.addRow("Next backup", self.lbl_next)
        summary.addLayout(form)
        self.lbl_dest_status, self.lbl_dest_reason = QLabel(), QLabel()
        for label in (self.lbl_dest_reason, self.lbl_dest_status):
            label.setWordWrap(True)
            summary.addWidget(label)
        self.lbl_dest_reason.hide()
        content.addWidget(self.summary_surface)
        self.backup_progress = QProgressBar()
        self.backup_progress.setRange(0, 0)
        self.backup_progress.setTextVisible(False)
        self.backup_progress.setFixedHeight(18)
        self.backup_progress.hide()
        content.addWidget(self.backup_progress)
        self.lbl_progress_detail = QLabel()
        self.lbl_progress_detail.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.lbl_progress_detail.setMinimumHeight(self.lbl_progress_detail.fontMetrics().height())
        self.lbl_progress_detail.hide()
        content.addWidget(self.lbl_progress_detail)
        self.history_section = QWidget()
        self.history_section.setObjectName("historySurface")
        self.history_section.setAttribute(Qt.WA_StyledBackground, True)
        history = QVBoxLayout(self.history_section)
        history.setContentsMargins(24, 16, 24, 16)
        title = QLabel("Recent activity")
        font = title.font()
        font.setBold(True)
        title.setFont(font)
        history.addWidget(title)
        self.activity_rows = []
        for _ in range(3):
            row = QHBoxLayout()
            timestamp, outcome = QLabel(), QLabel()
            timestamp.setWordWrap(True)
            outcome.setWordWrap(True)
            row.addWidget(timestamp, 1)
            row.addWidget(outcome, 2)
            history.addLayout(row)
            self.activity_rows.append((timestamp, outcome))
        content.addWidget(self.history_section)
        details = QWidget()
        form = QFormLayout(details)
        for caption, name in (("Last attempt:", "lbl_last_attempt"), ("Path:", "lbl_dest"), ("Repository:", "lbl_repo"), ("Integrity check:", "lbl_check"), ("Deep verify:", "lbl_verify"), ("Restore test:", "lbl_restore_test")):
            label = QLabel()
            setattr(self, name, label)
            form.addRow(caption, label)
        self.details_section = DisclosureSection("Details…", "Hide details", details)
        self.log_view = QPlainTextEdit()
        self.log_view.setReadOnly(True)
        self.log_view.setAccessibleName("Backup log")
        self.log_view.setMaximumBlockCount(2000)
        self.log_view.setPlaceholderText("Backup output appears here while running…")
        log = QWidget()
        log_layout = QVBoxLayout(log)
        log_layout.setContentsMargins(0, 0, 0, 0)
        log_layout.addWidget(self.log_view, 1)
        self.copy_summary_button = QPushButton("Copy summary")
        self.copy_summary_button.clicked.connect(lambda: QApplication.clipboard().setText(consumer.support_summary(self.log_view.toPlainText())))
        log_layout.addWidget(self.copy_summary_button, 0, Qt.AlignRight)
        self.log_section = DisclosureSection("Show log", "Hide log", log)
        footer = QHBoxLayout()
        footer.addWidget(self.details_section.toggle)
        footer.addWidget(self.log_section.toggle)
        footer.addStretch()
        content.addLayout(footer)
        content.addWidget(self.details_section)
        content.addWidget(self.log_section, 1)
